### ISSUE TITLE
An API which automatically validates its inputs

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/wasm-c-api#123]
It appears `wasm_module_new` / `Module::make` does not perform validation. The API provides `wasm_module_validate` / `Module::validate` which can be used to explicitly validate, however it's easy to forget to use these.

It would make the API safer if `wasm_module_new` / `Module::make` performed validation, and there were additional functions with evocative names, such as `wasm_module_new_unchecked` / `Module::make_unchecked`, for creating a module without validation.

**Comment by rossberg** [comment]
Hm, I'm pretty sure that module_new performs validation in the V8 prototype (it essentially invokes the JS WebAssembly.Module constructor). That's the intention anyway.

Should the API also provide unchecked versions?

**Comment by peterhuene** [comment]
In V8, I assume `wasm_module_new` is returning null when the module data is invalid?

As a user of the C API, my assumption was that `wasm_module_new` would validate and would return null on invalid module data; if that is indeed the case then I think we should document that behavior and fix Wasmtime to behave the same way.

:+1: on having adding an "unchecked" version that skips validation (if possible) since `wasm_module_validate` exists.

**Comment by rossberg** [comment]
@peterhuene, yes, you should get null. Any factory methods can return null. And yes, there should be documentation of that fact -- any documentation whatsoever, for that matter. :)

The wasm_module_new and _validate functions should also have an optional out parameter for getting possible error reports in some form.

**Comment by peterhuene** [comment]
Thanks for the confirmation. That's what my use of the C API was assuming.

@sunfishcode I think we should fix this in Wasmtime to validate for `wasm_module_new` then.

**Comment by sunfishcode** [comment]
@peterhuene Agreed. I'll close the issue here, and follow up on the Wasmtime side.
