### ISSUE TITLE
please close : noob error - API is fine.

### ISSUE THREAD

**Issue by adv-sw** [WebAssembly/wasm-c-api#140]
Callbacks sometimes need access to memory. Memory is instance specific.
Hence callbacks need to be able to securely identify the instance they are called from.

Proposed solution:

Please extended  C-API as follows to add a void* parameter to callbacks.

wasm_trap_t* my_callback(const wasm_val_t args[], wasm_val_t results[], *void *user*)

... which is assigned using (proposed) WASM_API_EXTERN void wasm_instance_userdata(const wasm_instance_t*, void *user);

Embedders can then cast their void pointer to that instance's wasm_memory_t pointer or a more complex struct depending on their needs.

wasm_func_new_with_env accepts a  similar void* however the parameter is not instance specific.

**Comment by rossberg** [comment]
Hm, it seems like wasm_instance_userdata already exists, it's just named wasm_instance_set_host_info. ;)

But I'm afraid there is no built-in notion of a "caller's instance" that could be exposed. Functions are stand-alone objects that aren't necessarily called from inside a Wasm instance -- for example, when the host calls them through wasm_func_call, which may e.g. happen in another callback. Moreover, even when the call does come from an instance, that information is not typically passed along in an engine. So the API cannot actually provide this information.

FWIW, caller identity is usually considered a poor basis for security. In fact, for JS, some security folks have long fought to get func.caller removed from the language, because it actually is a security hazard (it's a side channel that leaks information to the callee).

**Comment by adv-sw** [comment]
Obviously an instance calls the callback, Andreas and therefore that instance can either pass itself or something attached to it to a callback. Lacking the 'notion' required here is why this is an issue. Obv callbacks that aren't the result of an instance doing something don't go through this mechanism. 

Re: you security concern. we're trusted side. please allow us to deliver in a performant way. if you don't like what we're doing, don't use our implementation. the API should however allow us to perform necessary routing of required data. 

This is an APU not language issue.

What you 'cannot' do has been implemented (sub-optimally) by wasmtime_func_new_with_env &  wasmtime_caller_export_get. I'm not suggesting folding that particular implementation back to wasm-c-api as its sub-optimal, but it does provide proof of principle.

Please reconsider your stance. You're incorrect.

**Comment by adv-sw** [comment]
FWIW, caller identity is required so we can access caller memory to do actual stuff. this is required beyond single instance per store. For now I have to duplicate stores unnecessarily to work around the limitation of the current API. Thank you for your hard work, we must go further :)

**Comment by adv-sw** [comment]
wasm_instance_set_host_info isn't in the wasm.h in this repository, though a search found it in somebody's rust implementation. if that's the call you're refering to, sounds like it'll do. just need a means of getting that parameter into appropriate callbacks.

**Comment by jakobkummerow** [comment]
Maybe I'm missing something, but... memories are per-`Store`, not per instance. Functions are also per `Store`. If you use `wasm_func_new_with_env` to create functions, you can pass along a pointer to the same `Store`'s memory (or any other `void*` pointer of your choice, e.g. if you need even more information: store, instance, memory, user data, ...). Calling a function from a different `Store` than it was created in is invalid anyway, I believe. Once the function is called, its `void* env` is passed along to the callback. Shouldn't that cover your use case?

**Comment by adv-sw** [comment]
if memory is indeed per store rather than per instance, yes.

however if that's the case, I'm failing to understand the point of an instance.

a solid architecture is thing gets compiled from intermediate to target once, even if instantiated multiple times.

auto store = wasm_store_new(__engine);
auto module = wasm_module_new(m_store, &intermediate_binary);

store/module get the intermediate, so doing that multiple times, as is my current workaround & what you're suggesting is suboptimal in the case of multiple instances of some program.

**Comment by rossberg** [comment]
> Obviously an instance calls the callback

Not so, as I already said. "Callbacks" are just host-defined functions. Like regular Wasm functions they can be called from inside and outside Wasm. In neither case, the caller or the callee can tell the difference. That is intentional -- host functions are supposed to be able to emulate Wasm functions.

> and therefore that instance can either pass itself or something attached to it to a callback

Sure it can do so itself, explicitly, as a parameter to a regular function call or through the env mechanism. But if I understand correctly, you seem to expect that the API _implicitly_ produces information about the caller from somewhere. But engines don't pass along that information in their internal calling conventions. That would be additional overhead on every call. The API cannot change that, e.g. in the V8 implementation of the API, this information simply does not exist.

> wasm_instance_set_host_info isn't in the wasm.h in this repository

It is, it is created by the macro expansion of `WASM_DECLARE_REF(instance)`.

> if memory is indeed per store rather than per instance, yes but that sounds incorrect.

I honestly have no idea what you mean. As @jakobkummerow points out, memories are not tied to instances. Like functions, memories are stand-alone objects that can be created elsewhere and shared across instances if desired. Inversely, in the future of multi-memories, a single instance can reference as many memories as it likes. It is an N-to-N relation, not 1-to-1.

**Comment by adv-sw** [comment]
we have enough disagreement over something simple here that I'll just fork it mate.

**Comment by adv-sw** [comment]
there may be circumstances where you want to share *some* memory between *some* instances, but in general instances of programs run in their own address space. you've got an architecture weirdness here. I'll bash it to suit my needs when multiple instance overhead of doing it your way becomes an issue.

**Comment by adv-sw** [comment]
just because you can share memory between instances doesn't mean that's normally what you want to do. that is the exception, not the rule. having a small overhead for doing things that way is acceptable, when you must do it. a bit like pipes on a host. its a form of inter-process communication.

**Comment by adv-sw** [comment]
Re:   wassm_instance_set_host_info created by the macro expansion of WASM_DECLARE_REF(instance).

thanks. I'm all for macro cleverness, but perhaps not in a core api header file :)

**Comment by adv-sw** [comment]
what is the purpose of the user void * assigned in wasm_instance_set_host_info if not as I've requested, please.

**Comment by adv-sw** [comment]
I share your your concern over parameter overhead to callbacks.

wasm_func_new_with_env already has a void *

if that void * was replaced by the calling wasm_instance_t * (where appropriate), the void * currently a parameter there could be queried where necessary using wasm_instance_get_host_info or whatever you've called it. everyone happy unless there remains an objection.

**Comment by adv-sw** [comment]
I apologize. As has been explained to me, wasm_func_new_with_env can be created once per instance, thereby getting me an instance specific parameter in callbacks without the need to change anything.

sorry andreas., please delete. there exists a means to do what I want already. you have a solid architecture as I'm sure you already know & I'm discovering :)
