### ISSUE TITLE
Avoid relying on host floating-point

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/wasm-c-api#46]
include/wasm.h:
```c
typedef float float32_t;
typedef double float64_t;
```
For maximum portability, it'd be best to use int32_t and int64_t here. wasm-c-api itself doesn't need to do any floating-point computation; it just needs to be able to pass values around verbatim.

**Comment by rossberg** [comment]
Hm, that would seem rather unwieldy in the 99% use case, esp since C cannot directly cast between those types. It is probably very rare that C would code care about the verbatim bit pattern of NaNs, given that it doesn't guarantee that itself. If we want to support bit-preserving passing of floats then I'd rather suggest adding special support for that, e.g. via auxiliary methods on val_t.

**Comment by sunfishcode** [comment]
I'm thinking of non-C languages using this too. But one option would be to switch to integer internally and add convenience routines to talk float/double, for the benefit of the 99% use case. #49 illustrates this idea.

**Comment by sunfishcode** [comment]
I no longer have a need for this for my projects, so closing.
