### ISSUE TITLE
Import/export matching by array position

### ISSUE THREAD

**Issue by AndrewScheidecker** [WebAssembly/wasm-c-api#81]
The current API matches imported externs to `wasm_importtype_t`, and exported externs to `wasm_exporttype_t` by position within an array:
```
own wasm_instance_t* wasm_instance_new(
  wasm_store_t*, const wasm_module_t*, const wasm_extern_t* const imports[]);

void wasm_instance_exports(const wasm_instance_t*, own wasm_extern_vec_t* out);
```

[WAVM's "native" API takes a separate vector of imports for each extern kind.](https://github.com/WAVM/WAVM/blob/4c09a90e3389d7e37024d6f44d9bbee5df52d401/Include/WAVM/Runtime/Runtime.h#L335) This would be hard to make forward compatible with new extern kinds, so it's probably not suitable for this API.

[V8 instantiation seems to expect a two-level dictionary indexed by module+name in the form of an object.](https://github.com/WebAssembly/wasm-c-api/blob/486d3fe3899b53420ac495b758940d972d3664bc/src/wasm-v8.cc#L2117)

[WAVM currently only exposes looking up an instance export by name.](https://github.com/WAVM/WAVM/blob/4c09a90e3389d7e37024d6f44d9bbee5df52d401/Include/WAVM/Runtime/Runtime.h#L380) [V8 seems to do the same](https://github.com/WebAssembly/wasm-c-api/blob/master/src/wasm-v8.cc#L2176).

Maybe `wasm_instance_new` should take a vector of module+name+extern tuples, and `wasm_instance_exports` should return a vector of name+extern tuples?

**Comment by rossberg** [comment]
The current design is very intentional. Wasm doesn't specify what import resolution means, and hosts may use arbitrary strategies like e.g. materialising modules/functions based on import names or type information. In general, that would require a callback-based mechanism (cf. #53), which in turn is difficult to handle, especially for foreign language bindings.

So the idea of the current design is that the embedder does the resolution outside in whatever way it sees fit and simply constructs an adequate vector for instantiation. That way the issue of import resolution is nicely decoupled while remaining fully general. Custom resolution abstractions can easily be built on top.

**Comment by AndrewScheidecker** [comment]
> So the idea of the current design is that the embedder does the resolution outside in whatever way it sees fit and simply constructs an adequate vector for instantiation.

Yes, I was only proposing to change the import binding to be by name instead of by index. However, I see that multiple imports may have the same module+name, so that wouldn't work.

The problem for WAVM is that it doesn't keep track of import indices in memory: it splits the imports into an array for each kind. I suppose I need to add a map from import index to kind-specific index.
